name: Exec unit test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2.2.0
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Install dependecies
        run: npm install

      - name: Run jest tests
        run: npm run test